-- create tables
CREATE TABLE public.points (
	x int4 NULL,
	y int4 NULL,
	geom public.geometry NULL,
	p_order int4 NOT NULL,
	CONSTRAINT points_pk PRIMARY KEY (p_order)
);
CREATE TABLE public.polygons (
	id int4 GENERATED ALWAYS AS IDENTITY NOT NULL,
	geom public.geometry NULL,
	CONSTRAINT polygons_pk PRIMARY KEY (id)
);
CREATE TABLE public.potential_rectangles (
	point1_id int4 NOT NULL,
	point2_id int4 NOT NULL,
	distance int4 NOT NULL,
	area int8 NOT NULL,
	geom public.geometry NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	CONSTRAINT potential_rectangles_pk PRIMARY KEY (id),
	CONSTRAINT potential_rectangles_points_fk FOREIGN KEY (point1_id) REFERENCES public.points(p_order),
	CONSTRAINT potential_rectangles_points_fk_1 FOREIGN KEY (point2_id) REFERENCES public.points(p_order)
);
-- upload the data (copy-paste, or load via psql COPY from CSV file)
-- genereting geoms from points
UPDATE public.points p 
SET geom = ST_MakePoint(p.x::double precision, p.y::double precision);

--generating polygon
WITH ordered AS (
  SELECT geom
  FROM points
  ORDER BY p_order
),
line AS (
  -- line that follows all points in order
  SELECT ST_MakeLine(geom) AS geom
  FROM ordered
),
closed_line AS (
  -- close the line by adding its start point to the end
  SELECT ST_AddPoint(geom, ST_StartPoint(geom)) AS geom
  FROM line
)
insert into public.polygons(geom)
SELECT ST_MakePolygon(geom) AS geom
FROM closed_line;

--- updating potential rectangles with their geoms
update potential_rectangles pr2 
set geom = (
select ST_MakeEnvelope(
  LEAST(p1.x , p2.x),
  LEAST(p1.y, p2.y),
  GREATEST(p1.x, p2.x),
  GREATEST(p1.y, p2.y)
) AS rect
from potential_rectangles pr 
join points p1 on pr.point1_id =p1.p_order 
join points p2 on pr.point2_id =p2.p_order 
where pr2.id=pr.id);
-- Finally ask for solution
select
	p1.geom ,
	p2.geom,
	pr.geom,
	p.geom,
	pr.area
from
	potential_rectangles pr
join polygons p on
	st_within(pr.geom, p.geom)
join points p1 on
	pr.point1_id = p1.p_order
join points p2 on
	pr.point2_id = p2.p_order
where
	p.id = 2 -- polygon 2 from final input, polygon 1 from example data
order by
	area desc
limit 1;